name: Welcome First-Time Contributor v3

on:
  pull_request_target:
    types: [opened]

permissions:
  issues: write
  pull-requests: write
  contents: read

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: Debug author association
        run: |
             echo "Author Association: ${{ github.event.pull_request.author_association }}"
             echo "User: ${{ github.event.pull_request.user.login }}"
             
      - name: Post welcome message if first-time contributor
        if: |
          github.event.pull_request.author_association == 'FIRST_TIMER' || 
          github.event.pull_request.author_association == 'FIRST_TIME_CONTRIBUTOR' || 
          github.event.pull_request.author_association == 'NONE' ||
          github.event.pull_request.author_association != 'CONTRIBUTOR'
          
        uses: actions/github-script@v7
        with:
          script: |
            const stickers = [
              "![🎉 Sticker](https://media.giphy.com/media/26ufdipQqU2lhNA4g/giphy.gif)",
              "![🚀 Sticker](https://media.giphy.com/media/duzpaTbCUy9Vu/giphy.gif)",
              "![👏 Sticker](https://media.giphy.com/media/l0MYt5jPR6QX5pnqM/giphy.gif)",
              "![🌟 Sticker](https://media.giphy.com/media/3oriO0OEd9QIDdllqo/giphy.gif)"
            ];

            const randomSticker = stickers[Math.floor(Math.random() * stickers.length)];

            const message = `
            🎉 Thank you @${context.payload.pull_request.user.login} for your **first contribution**! 🎉  

            ${randomSticker}

            We’re thrilled to have you join the project — welcome aboard! 🚀
            `;

            // Post a comment
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            });
          

